### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [antoinepirlot/Satunes#539]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7235345115#L4548

Diff log is tiny:
```
│ │ │   --- Satunes_v1.2.0/smali/R2/G.smali
│ │ ├── +++ io.github.antoinepirlot.satunes_35/smali/R2/G.smali
│ │ │ @@ -7489,15 +7489,15 @@
│ │ │      shl-int/2addr v0, v6
│ │ │  
│ │ │      .line 164
│ │ │      and-int/lit16 v0, v0, 0x380
│ │ │  
│ │ │      .line 165
│ │ │      .line 166
│ │ │ -    or-int/lit8 v10, v0, 0x8
│ │ │ +    or-int/lit8 v10, v0, 0x38
│ │ │  
│ │ │      .line 167
│ │ │      .line 168
│ │ │      const/4 v6, 0x0
│ │ │  
│ │ │      .line 169
│ │ │      const/4 v7, 0x0
```

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/802119bc1d2bc304eb986803290ad8323a4530ef

**Comment by antoinepirlot** [comment]
Hello @licaon-kter, I found the issue. I didn't updated the SDK to the latest version (I missed the update notification maybe 🙄) Now it builds correctly

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7278799928 The build failed again. Can you clean the cache and rebuild the apk?

**Comment by antoinepirlot** [comment]
Hello, I cleaned and rebuilt the apk. It works now 😊 De : linsuiEnvoyé le :dimanche 7 juillet 2024 09:23À : antoinepirlot/SatunesCc : Antoine; State changeObjet :Re: [antoinepirlot/Satunes] F-Droid can't build (Issue #539) https://gitlab.com/fdroid/fdroiddata/-/jobs/7278799928 The build failed again. Can you clean the cache and rebuild the apk?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by linsui** [comment]
It's fixed, thanks!

**Comment by licaon-kter** [comment]
reopen: https://gitlab.com/fdroid/fdroiddata/-/jobs/7562538227#L560

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/d313fc25a5f39db8d2998ded6e72961e47de085e

**Comment by antoinepirlot** [comment]
> thanks https://gitlab.com/fdroid/fdroiddata/-/commit/d313fc25a5f39db8d2998ded6e72961e47de085e

Thank you
